/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GuardianWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aiGuardian"
      | "execute"
      | "nonce"
      | "owner"
      | "updateGuardian"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Executed" | "GuardianUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "aiGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateGuardian",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "aiGuardian", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateGuardian",
    data: BytesLike
  ): Result;
}

export namespace ExecutedEvent {
  export type InputTuple = [
    to: AddressLike,
    value: BigNumberish,
    data: BytesLike,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    to: string,
    value: bigint,
    data: string,
    nonce: bigint
  ];
  export interface OutputObject {
    to: string;
    value: bigint;
    data: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardianUpdatedEvent {
  export type InputTuple = [oldGuardian: AddressLike, newGuardian: AddressLike];
  export type OutputTuple = [oldGuardian: string, newGuardian: string];
  export interface OutputObject {
    oldGuardian: string;
    newGuardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GuardianWallet extends BaseContract {
  connect(runner?: ContractRunner | null): GuardianWallet;
  waitForDeployment(): Promise<this>;

  interface: GuardianWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aiGuardian: TypedContractMethod<[], [string], "view">;

  execute: TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      guardianSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  nonce: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  updateGuardian: TypedContractMethod<
    [_newGuardian: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aiGuardian"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      guardianSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateGuardian"
  ): TypedContractMethod<[_newGuardian: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Executed"
  ): TypedContractEvent<
    ExecutedEvent.InputTuple,
    ExecutedEvent.OutputTuple,
    ExecutedEvent.OutputObject
  >;
  getEvent(
    key: "GuardianUpdated"
  ): TypedContractEvent<
    GuardianUpdatedEvent.InputTuple,
    GuardianUpdatedEvent.OutputTuple,
    GuardianUpdatedEvent.OutputObject
  >;

  filters: {
    "Executed(address,uint256,bytes,uint256)": TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
    Executed: TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;

    "GuardianUpdated(address,address)": TypedContractEvent<
      GuardianUpdatedEvent.InputTuple,
      GuardianUpdatedEvent.OutputTuple,
      GuardianUpdatedEvent.OutputObject
    >;
    GuardianUpdated: TypedContractEvent<
      GuardianUpdatedEvent.InputTuple,
      GuardianUpdatedEvent.OutputTuple,
      GuardianUpdatedEvent.OutputObject
    >;
  };
}
