/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MerchantPay,
  MerchantPayInterface,
} from "../../../contracts/MerchantPay.sol/MerchantPay";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "merchant",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "orderId",
        type: "string",
      },
    ],
    name: "PaymentReceived",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "merchant",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "orderId",
        type: "string",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506102a28061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610029575f3560e01c806384a602321461002d575b5f80fd5b61004061003b36600461016c565b610042565b005b6040516323b872dd60e01b81523360048201526001600160a01b038581166024830152604482018590528616906323b872dd906064016020604051808303815f875af1158015610094573d5f803e3d5ffd5b505050506040513d601f19601f820116820180604052508101906100b891906101ff565b6100f95760405162461bcd60e51b815260206004820152600e60248201526d14185e5b595b9d0819985a5b195960921b604482015260640160405180910390fd5b836001600160a01b0316336001600160a01b03167f57f6b5ae1c70962785ee79f859a9363b398d5f7288ba67f81530bcd8ad72d8f3878686866040516101429493929190610225565b60405180910390a35050505050565b80356001600160a01b0381168114610167575f80fd5b919050565b5f805f805f60808688031215610180575f80fd5b61018986610151565b945061019760208701610151565b935060408601359250606086013567ffffffffffffffff808211156101ba575f80fd5b818801915088601f8301126101cd575f80fd5b8135818111156101db575f80fd5b8960208285010111156101ec575f80fd5b9699959850939650602001949392505050565b5f6020828403121561020f575f80fd5b8151801515811461021e575f80fd5b9392505050565b6001600160a01b0385168152602081018490526060604082018190528101829052818360808301375f818301608090810191909152601f909201601f19160101939250505056fea26469706673582212200d513b327ec1e6d8324b3ca778ea1deeaf5747b5e98904637d3383669179146164736f6c63430008180033";

type MerchantPayConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MerchantPayConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MerchantPay__factory extends ContractFactory {
  constructor(...args: MerchantPayConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MerchantPay & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MerchantPay__factory {
    return super.connect(runner) as MerchantPay__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MerchantPayInterface {
    return new Interface(_abi) as MerchantPayInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MerchantPay {
    return new Contract(address, _abi, runner) as unknown as MerchantPay;
  }
}
